In [22]:
import numpy as np

def place_ships(input):
    print ("test")
    
def play_game(input):
    print ("test")
    Matrix = [[0 for x in range(10)] for y in range(10)] 
    #print (Matrix)
    print(np.matrix(Matrix))

def create_game(input):
    print ("test")
    
count = 0
while(int(count) != 99):
    #count is taken as a string so you must use int(count) to get the integer value of the input
    count = input("Welcome to Battleship!" + "\n" + "Enter a coorresponding number:" + 
                  "\n" + "1. Play Game" + "\n" + "99. Exit Game" + "\n")

    if int(count) == 1:
        play_game(count)
    elif int(count) == 99:
        #print ("test1")
        break
        
print ("Goodbye!")

Welcome to Battleship!
Enter a coorresponding number:
1. Play Game
99. Exit Game
1
test
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Welcome to Battleship!
Enter a coorresponding number:
1. Play Game
99. Exit Game
99
Goodbye!
